updating the config file

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -32,4 +32,4 @@ jobs:
           DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
         run: |
           echo "Listing deployed files..."
-          databricks workspace ls "/Workspace/Users/aradhana.dubey@diggibyte.com/.bundle/recon-bundle/dev/files/config/" || echo "❌ Config folder NOT found!"
+          databricks workspace ls "/Workspace/Users/aradhana.dubey@diggibyte.com/.bundle/recon-bundle/dev/files/config/" || echo " Config folder NOT found!"
